"""
ORM model for the NOTIFICATIONS table (Host Oracle DB).

Schema (from host_database.sql):
    NOTIFICATIONS (
        id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        host_id      NUMBER NOT NULL REFERENCES HOSTS(id) ON DELETE CASCADE,
        type         VARCHAR2(50) NOT NULL,
        title        VARCHAR2(255),
        body         CLOB,
        related_type VARCHAR2(50),   -- 'booking','review','payment','support_ticket'
        related_id   VARCHAR2(64),   -- string, NOT a number: Client side (CockroachDB)
                                      -- uses UUIDs for booking/review primary keys.
        is_read      NUMBER(1) DEFAULT 0,
        created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
"""

from datetime import datetime
from app.extensions import db


class Notification(db.Model):
    __tablename__ = "NOTIFICATIONS"

    id           = db.Column(db.Integer, db.Identity(), primary_key=True)
    host_id      = db.Column(
        db.Integer,
        db.ForeignKey("HOSTS.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    type         = db.Column(db.String(50), nullable=False)
    title        = db.Column(db.String(255))
    body         = db.Column(db.Text)
    related_type = db.Column(db.String(50))   # 'booking' | 'review' | 'payment'
    related_id   = db.Column(db.String(64))   # CockroachDB UUID (or any id), stored as text
    is_read      = db.Column(db.Integer, default=0)   # Oracle NUMBER(1)
    created_at   = db.Column(db.DateTime, default=datetime.utcnow)

    def to_dict(self):
        return {
            "id":           self.id,
            "host_id":      self.host_id,
            "type":         self.type,
            "title":        self.title,
            "body":         self.body,
            "related_type": self.related_type,
            "related_id":   self.related_id,
            "is_read":      bool(self.is_read),
            "created_at":   self.created_at.isoformat() if self.created_at else None,
        }

    def __repr__(self):
        return f"<Notification id={self.id} host={self.host_id} type={self.type}>"