"""initial_schema

Revision ID: e4d962deb3a7
Revises: 
Create Date: 2026-06-25 00:52:19.487580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4d962deb3a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def table_exists(table_name: str) -> bool:
    bind = op.get_bind()
    return bind.dialect.has_table(bind, table_name)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not table_exists('admin_accounts'):
        op.create_table('admin_accounts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.Column('email', sa.String(length=100), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_admin_accounts_email'), 'admin_accounts', ['email'], unique=True)
        op.create_index(op.f('ix_admin_accounts_id'), 'admin_accounts', ['id'], unique=False)
        op.create_index(op.f('ix_admin_accounts_username'), 'admin_accounts', ['username'], unique=True)

    if not table_exists('admin_audit_log'):
        op.create_table('admin_audit_log',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('admin_id', sa.Integer(), nullable=True),
        sa.Column('admin_username', sa.String(length=50), nullable=True),
        sa.Column('action', sa.String(length=100), nullable=False),
        sa.Column('details', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_admin_audit_log_id'), 'admin_audit_log', ['id'], unique=False)

    if not table_exists('disputes'):
        op.create_table('disputes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('booking_external_id', sa.String(length=100), nullable=True),
        sa.Column('filed_by', sa.String(length=100), nullable=True),
        sa.Column('filed_by_email', sa.String(length=100), nullable=True),
        sa.Column('reason', sa.Text(), nullable=False),
        sa.Column('evidence', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('resolution', sa.Text(), nullable=True),
        sa.Column('resolved_by', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_disputes_booking_external_id'), 'disputes', ['booking_external_id'], unique=False)
        op.create_index(op.f('ix_disputes_id'), 'disputes', ['id'], unique=False)
        op.create_index(op.f('ix_disputes_status'), 'disputes', ['status'], unique=False)

    if not table_exists('listings'):
        op.create_table('listings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('external_id', sa.String(length=100), nullable=True),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('host_external_id', sa.String(length=100), nullable=True),
        sa.Column('host_email', sa.String(length=100), nullable=True),
        sa.Column('location', sa.String(length=255), nullable=True),
        sa.Column('price_per_night', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('rejection_reason', sa.Text(), nullable=True),
        sa.Column('photo_url', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_listings_external_id'), 'listings', ['external_id'], unique=True)
        op.create_index(op.f('ix_listings_host_external_id'), 'listings', ['host_external_id'], unique=False)
        op.create_index(op.f('ix_listings_id'), 'listings', ['id'], unique=False)
        op.create_index(op.f('ix_listings_status'), 'listings', ['status'], unique=False)

    if not table_exists('support_tickets'):
        op.create_table('support_tickets',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('subject', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('requester_name', sa.String(length=100), nullable=True),
        sa.Column('requester_email', sa.String(length=100), nullable=True),
        sa.Column('category', sa.String(length=50), nullable=True),
        sa.Column('priority', sa.String(length=20), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('assigned_to', sa.String(length=50), nullable=True),
        sa.Column('resolution', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_support_tickets_category'), 'support_tickets', ['category'], unique=False)
        op.create_index(op.f('ix_support_tickets_id'), 'support_tickets', ['id'], unique=False)
        op.create_index(op.f('ix_support_tickets_priority'), 'support_tickets', ['priority'], unique=False)
        op.create_index(op.f('ix_support_tickets_requester_email'), 'support_tickets', ['requester_email'], unique=False)
        op.create_index(op.f('ix_support_tickets_status'), 'support_tickets', ['status'], unique=False)

    if not table_exists('system_settings'):
        op.create_table('system_settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('key', sa.String(length=100), nullable=False),
        sa.Column('value', sa.Text(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
        op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)

    if not table_exists('users'):
        op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.Column('email', sa.String(length=100), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('is_verified', sa.Boolean(), nullable=True),
        sa.Column('verification_code', sa.String(length=6), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
        op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
        op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    if not table_exists('withdrawals'):
        op.create_table('withdrawals',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('external_id', sa.String(length=100), nullable=True),
        sa.Column('host_external_id', sa.String(length=100), nullable=True),
        sa.Column('host_name', sa.String(length=100), nullable=True),
        sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('method', sa.String(length=50), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('rejection_reason', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_withdrawals_external_id'), 'withdrawals', ['external_id'], unique=True)
        op.create_index(op.f('ix_withdrawals_host_external_id'), 'withdrawals', ['host_external_id'], unique=False)
        op.create_index(op.f('ix_withdrawals_id'), 'withdrawals', ['id'], unique=False)
        op.create_index(op.f('ix_withdrawals_status'), 'withdrawals', ['status'], unique=False)

    if not table_exists('bookings'):
        op.create_table('bookings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('external_id', sa.String(length=100), nullable=True),
        sa.Column('listing_id', sa.Integer(), nullable=True),
        sa.Column('listing_title', sa.String(length=255), nullable=True),
        sa.Column('guest_name', sa.String(length=100), nullable=True),
        sa.Column('guest_email', sa.String(length=100), nullable=True),
        sa.Column('host_external_id', sa.String(length=100), nullable=True),
        sa.Column('check_in', sa.DateTime(timezone=True), nullable=True),
        sa.Column('check_out', sa.DateTime(timezone=True), nullable=True),
        sa.Column('nights', sa.Integer(), nullable=True),
        sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('cancellation_reason', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_bookings_external_id'), 'bookings', ['external_id'], unique=True)
        op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
        op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
        op.create_index('ix_bookings_status_created', 'bookings', ['status', 'created_at'], unique=False)

    if not table_exists('reviews'):
        op.create_table('reviews',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('external_id', sa.String(length=100), nullable=True),
        sa.Column('listing_id', sa.Integer(), nullable=True),
        sa.Column('listing_title', sa.String(length=255), nullable=True),
        sa.Column('guest_name', sa.String(length=100), nullable=True),
        sa.Column('guest_email', sa.String(length=100), nullable=True),
        sa.Column('rating', sa.Integer(), nullable=True),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.Column('is_hidden', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_reviews_external_id'), 'reviews', ['external_id'], unique=True)
        op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)

    if not table_exists('payments'):
        op.create_table('payments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('external_id', sa.String(length=100), nullable=True),
        sa.Column('booking_id', sa.Integer(), nullable=True),
        sa.Column('booking_external_id', sa.String(length=100), nullable=True),
        sa.Column('payer_name', sa.String(length=100), nullable=True),
        sa.Column('payer_email', sa.String(length=100), nullable=True),
        sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('currency', sa.String(length=10), nullable=True),
        sa.Column('method', sa.String(length=50), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('refund_reason', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_payments_external_id'), 'payments', ['external_id'], unique=True)
        op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
        op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_external_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_external_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_bookings_status_created', table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_external_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_withdrawals_status'), table_name='withdrawals')
    op.drop_index(op.f('ix_withdrawals_id'), table_name='withdrawals')
    op.drop_index(op.f('ix_withdrawals_host_external_id'), table_name='withdrawals')
    op.drop_index(op.f('ix_withdrawals_external_id'), table_name='withdrawals')
    op.drop_table('withdrawals')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_support_tickets_status'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_requester_email'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_priority'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_category'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_listings_status'), table_name='listings')
    op.drop_index(op.f('ix_listings_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_host_external_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_external_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_disputes_status'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_booking_external_id'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_admin_audit_log_id'), table_name='admin_audit_log')
    op.drop_table('admin_audit_log')
    op.drop_index(op.f('ix_admin_accounts_username'), table_name='admin_accounts')
    op.drop_index(op.f('ix_admin_accounts_id'), table_name='admin_accounts')
    op.drop_index(op.f('ix_admin_accounts_email'), table_name='admin_accounts')
    op.drop_table('admin_accounts')
    # ### end Alembic commands ###
